_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  announcements_feed: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_ex: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fitvids: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  jquery_ui: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  movie_autofill: 0
  movie_ratings: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  rest: 0
  restui: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_autocomplete: 0
  serialization: 0
  shortcut: 0
  superfish: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  tb_megamenu: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_options_custom: 0
  webform_ui: 0
  yearonly: 0
  ds: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  nc_theme: 0
profile: standard
