_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 85742c00-01e8-4e0b-a06f-aba10a1a2d2d
name: 'Fanshawe Learning'
mail: elsnkazimov@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /movie-card
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
config_sync_directory: config/sync
