name: Deploy Master to Pantheon
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TERMINUS_ALLOW_UNSUPPORTED_NEWER_PHP: "1"
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Set Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        set -x
        echo ${{ secrets.KNOWN_HOSTS }}
        git remote add pantheon $pantheon_repo
        git fetch pantheon
        git merge pantheon/master --allow-unrelated-histories --no-edit
        git push pantheon HEAD:master
        commit_message=$(git log -1 --pretty=%B)
        terminus env:deploy $pantheon_site_name.test --note="Automated deploy: $commit_message"
        terminus env:deploy $pantheon_site_name.live --note="Automated deploy: $commit_message"

# <!-- Test #4 change for Git -->

